create table tb_alunos (
    id number GENERATED by default as Identity primary key,
    nome varchar(50),
    email varchar(100) unique
);

insert into tb_alunos (nome, email) VALUES ('Luana', 'luana@techne.com');

select * from tb_alunos;

declare
    v_nome varchar(10);
begin
    select nome into v_nome from tb_alunos where id = 1;
    dbms_output.put_line(v_nome);
end;